"""Alembic environment.

The database URL and the target metadata both come from the application, so
there is one source of truth: ``DATABASE_URL`` configures the app and the
migrations alike, and ``alembic.ini`` carries no connection string to fall out
of step with it.
"""

from __future__ import annotations

from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

from app.config import settings
from app.database import Base
from app import models  # noqa: F401  (imports every model onto Base.metadata)

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# A caller may already have set the URL (app.migrate does, and the tests
# point it at a scratch database); only fall back to the app's own setting.
if not config.get_main_option("sqlalchemy.url", None):
    config.set_main_option("sqlalchemy.url", settings.database_url.replace("%", "%%"))

target_metadata = Base.metadata


def _include_object(obj, name, type_, reflected, compare_to) -> bool:
    """Keep autogenerate focused on the tables this project owns."""
    if type_ == "table" and name == "alembic_version":
        return False
    return True


def _common_options() -> dict:
    url = config.get_main_option("sqlalchemy.url") or settings.database_url
    return {
        "target_metadata": target_metadata,
        "include_object": _include_object,
        # Without this, a change to a column's type or nullability is silently
        # left out of an autogenerated migration.
        "compare_type": True,
        "compare_server_default": True,
        # SQLite cannot ALTER most things in place; batch mode rewrites the
        # table instead, so the same migration runs on SQLite and PostgreSQL.
        "render_as_batch": url.startswith("sqlite"),
    }


def run_migrations_offline() -> None:
    """Emit SQL to stdout instead of running it, for review or a DBA."""
    context.configure(
        url=config.get_main_option("sqlalchemy.url") or settings.database_url,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        **_common_options(),
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(connection=connection, **_common_options())
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
