"""baseline schema

Revision ID: aac967df5561
Revises: 
Create Date: 2026-09-24 12:49:24.785252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aac967df5561'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_email', sa.String(length=320), nullable=False),
    sa.Column('actor_name', sa.String(length=200), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('entity_label', sa.String(length=300), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index('ix_audit_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_actor_email'), ['actor_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index('ix_audit_occurred', ['occurred_at'], unique=False)

    op.create_table('certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_no', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('cir_number', sa.String(length=300), nullable=True),
    sa.Column('file_number', sa.String(length=200), nullable=True),
    sa.Column('section', sa.String(length=40), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('kind', sa.String(length=120), nullable=True),
    sa.Column('reg_type', sa.String(length=40), nullable=True),
    sa.Column('formulation', sa.String(length=40), nullable=True),
    sa.Column('shelf_life', sa.String(length=80), nullable=True),
    sa.Column('source_file', sa.String(length=400), nullable=True),
    sa.Column('source_dir', sa.String(length=400), nullable=True),
    sa.Column('dose_head', sa.Text(), nullable=True),
    sa.Column('dose_raw', sa.Text(), nullable=True),
    sa.Column('dose_parsed', sa.Boolean(), nullable=False),
    sa.Column('crops_summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_no', name='uq_certificates_item_no')
    )
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certificates_category'), ['category'], unique=False)
        batch_op.create_index('ix_certificates_cir', ['cir_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificates_reg_type'), ['reg_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificates_section'), ['section'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificates_title'), ['title'], unique=False)

    op.create_table('clauses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint')
    )
    op.create_table('endorsements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rc_meeting', sa.Integer(), nullable=False),
    sa.Column('agenda_ref', sa.String(length=40), nullable=True),
    sa.Column('page', sa.String(length=20), nullable=True),
    sa.Column('en_number', sa.Text(), nullable=True),
    sa.Column('applicant', sa.String(length=400), nullable=True),
    sa.Column('product', sa.String(length=400), nullable=True),
    sa.Column('cir_number', sa.String(length=300), nullable=True),
    sa.Column('endorsement_type', sa.String(length=200), nullable=True),
    sa.Column('request', sa.Text(), nullable=True),
    sa.Column('decision', sa.String(length=120), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('caveat', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('endorsements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_endorsements_applicant'), ['applicant'], unique=False)
        batch_op.create_index(batch_op.f('ix_endorsements_decision'), ['decision'], unique=False)
        batch_op.create_index('ix_endorsements_en', ['en_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_endorsements_endorsement_type'), ['endorsement_type'], unique=False)
        batch_op.create_index('ix_endorsements_meeting', ['rc_meeting'], unique=False)
        batch_op.create_index(batch_op.f('ix_endorsements_product'), ['product'], unique=False)

    op.create_table('import_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('technical', sa.String(length=400), nullable=False),
    sa.Column('cir_number', sa.String(length=300), nullable=True),
    sa.Column('via', sa.String(length=40), nullable=True),
    sa.Column('supplier', sa.String(length=400), nullable=True),
    sa.Column('manufacturers', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_sources_technical'), ['technical'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_sources_via'), ['via'], unique=False)

    op.create_table('licences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('licence_number', sa.String(length=120), nullable=False),
    sa.Column('licence_type', sa.Enum('manufacture', 'sale', 'stock_and_sale', 'storage', 'import_export', 'principal_certificate', name='licencetype', native_enum=False, length=64), nullable=False),
    sa.Column('holder_name', sa.String(length=200), nullable=False),
    sa.Column('site_name', sa.String(length=200), nullable=True),
    sa.Column('site_address', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=80), nullable=False),
    sa.Column('issuing_authority', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('active', 'under_renewal', 'suspended', 'cancelled', 'surrendered', name='compliancestatus', native_enum=False, length=64), nullable=False),
    sa.Column('document_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('valid_until IS NULL OR valid_from IS NULL OR valid_until >= valid_from', name='ck_licences_validity_window'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state', 'licence_number', name='uq_licences_state_number')
    )
    with op.batch_alter_table('licences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_licences_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_licences_valid_until'), ['valid_until'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('brand_name', sa.String(length=200), nullable=True),
    sa.Column('active_ingredient', sa.String(length=300), nullable=False),
    sa.Column('concentration', sa.String(length=50), nullable=True),
    sa.Column('cas_number', sa.String(length=50), nullable=True),
    sa.Column('category', sa.Enum('insecticide', 'herbicide', 'fungicide', 'rodenticide', 'nematicide', 'plant_growth_regulator', 'biopesticide', 'other', name='productcategory', native_enum=False, length=64), nullable=False),
    sa.Column('formulation_type', sa.Enum('TC', 'TK', 'EC', 'SC', 'SL', 'WP', 'WG', 'GR', 'DP', 'ULV', 'OTHER', name='formulationtype', native_enum=False, length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'formulation_type', name='uq_products_name_formulation')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_cas_number'), ['cas_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_name'), ['name'], unique=False)

    op.create_table('text_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('viewer', 'editor', 'admin', name='role', native_enum=False, length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)

    op.create_table('api_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('lookup', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_tokens_lookup'), ['lookup'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('certificate_clauses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('certificate_id', sa.Integer(), nullable=False),
    sa.Column('clause_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['certificate_id'], ['certificates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['clause_id'], ['clauses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('certificate_id', 'position', name='uq_certificate_clause_position')
    )
    with op.batch_alter_table('certificate_clauses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certificate_clauses_certificate_id'), ['certificate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificate_clauses_clause_id'), ['clause_id'], unique=False)

    op.create_table('certificate_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('certificate_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('text_block_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['certificate_id'], ['certificates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['text_block_id'], ['text_blocks.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('certificate_id', 'name', name='uq_certificate_section_name')
    )
    with op.batch_alter_table('certificate_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certificate_sections_certificate_id'), ['certificate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificate_sections_text_block_id'), ['text_block_id'], unique=False)

    op.create_table('dose_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('certificate_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('cells', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['certificate_id'], ['certificates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dose_rows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dose_rows_certificate_id'), ['certificate_id'], unique=False)

    op.create_table('licence_products',
    sa.Column('licence_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['licence_id'], ['licences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('licence_id', 'product_id')
    )
    op.create_table('registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('registration_number', sa.String(length=120), nullable=False),
    sa.Column('section', sa.Enum('9(3)', '9(3B)', '9(4)', '9(3)-import', '9(4)-import', name='registrationsection', native_enum=False, length=64), nullable=False),
    sa.Column('purpose', sa.Enum('manufacture', 'formulation', 'import', 'export', 'repacking', name='registrationpurpose', native_enum=False, length=64), nullable=False),
    sa.Column('registrant_name', sa.String(length=200), nullable=False),
    sa.Column('issuing_authority', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('active', 'under_renewal', 'suspended', 'cancelled', 'surrendered', name='compliancestatus', native_enum=False, length=64), nullable=False),
    sa.Column('document_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('valid_until IS NULL OR valid_from IS NULL OR valid_until >= valid_from', name='ck_registrations_validity_window'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number', name='uq_registrations_number')
    )
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registrations_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registrations_valid_until'), ['valid_until'], unique=False)

    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_session_hash'), ['session_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('label_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=True),
    sa.Column('approval_number', sa.String(length=120), nullable=False),
    sa.Column('label_version', sa.String(length=50), nullable=False),
    sa.Column('leaflet_version', sa.String(length=50), nullable=True),
    sa.Column('approving_authority', sa.String(length=200), nullable=False),
    sa.Column('languages', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('active', 'under_renewal', 'suspended', 'cancelled', 'surrendered', name='compliancestatus', native_enum=False, length=64), nullable=False),
    sa.Column('document_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('valid_until IS NULL OR valid_from IS NULL OR valid_until >= valid_from', name='ck_label_approvals_validity_window'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('approval_number', 'label_version', name='uq_label_approval_number_version')
    )
    with op.batch_alter_table('label_approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_label_approvals_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_label_approvals_registration_id'), ['registration_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_label_approvals_valid_until'), ['valid_until'], unique=False)

    op.create_table('state_sale_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=80), nullable=False),
    sa.Column('permission_number', sa.String(length=120), nullable=False),
    sa.Column('licensing_authority', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('active', 'under_renewal', 'suspended', 'cancelled', 'surrendered', name='compliancestatus', native_enum=False, length=64), nullable=False),
    sa.Column('document_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('valid_until IS NULL OR valid_from IS NULL OR valid_until >= valid_from', name='ck_state_sale_permissions_validity_window'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state', 'permission_number', name='uq_sale_permission_state_number')
    )
    with op.batch_alter_table('state_sale_permissions', schema=None) as batch_op:
        batch_op.create_index('ix_sale_permissions_product_state', ['product_id', 'state'], unique=False)
        batch_op.create_index(batch_op.f('ix_state_sale_permissions_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_state_sale_permissions_registration_id'), ['registration_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_state_sale_permissions_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_state_sale_permissions_valid_until'), ['valid_until'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('state_sale_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_state_sale_permissions_valid_until'))
        batch_op.drop_index(batch_op.f('ix_state_sale_permissions_state'))
        batch_op.drop_index(batch_op.f('ix_state_sale_permissions_registration_id'))
        batch_op.drop_index(batch_op.f('ix_state_sale_permissions_product_id'))
        batch_op.drop_index('ix_sale_permissions_product_state')

    op.drop_table('state_sale_permissions')
    with op.batch_alter_table('label_approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_label_approvals_valid_until'))
        batch_op.drop_index(batch_op.f('ix_label_approvals_registration_id'))
        batch_op.drop_index(batch_op.f('ix_label_approvals_product_id'))

    op.drop_table('label_approvals')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_session_hash'))

    op.drop_table('user_sessions')
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registrations_valid_until'))
        batch_op.drop_index(batch_op.f('ix_registrations_product_id'))

    op.drop_table('registrations')
    op.drop_table('licence_products')
    with op.batch_alter_table('dose_rows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dose_rows_certificate_id'))

    op.drop_table('dose_rows')
    with op.batch_alter_table('certificate_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certificate_sections_text_block_id'))
        batch_op.drop_index(batch_op.f('ix_certificate_sections_certificate_id'))

    op.drop_table('certificate_sections')
    with op.batch_alter_table('certificate_clauses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certificate_clauses_clause_id'))
        batch_op.drop_index(batch_op.f('ix_certificate_clauses_certificate_id'))

    op.drop_table('certificate_clauses')
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_api_tokens_lookup'))

    op.drop_table('api_tokens')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('text_blocks')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_name'))
        batch_op.drop_index(batch_op.f('ix_products_cas_number'))

    op.drop_table('products')
    with op.batch_alter_table('licences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_licences_valid_until'))
        batch_op.drop_index(batch_op.f('ix_licences_state'))

    op.drop_table('licences')
    with op.batch_alter_table('import_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_sources_via'))
        batch_op.drop_index(batch_op.f('ix_import_sources_technical'))

    op.drop_table('import_sources')
    with op.batch_alter_table('endorsements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_endorsements_product'))
        batch_op.drop_index('ix_endorsements_meeting')
        batch_op.drop_index(batch_op.f('ix_endorsements_endorsement_type'))
        batch_op.drop_index('ix_endorsements_en')
        batch_op.drop_index(batch_op.f('ix_endorsements_decision'))
        batch_op.drop_index(batch_op.f('ix_endorsements_applicant'))

    op.drop_table('endorsements')
    op.drop_table('clauses')
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certificates_title'))
        batch_op.drop_index(batch_op.f('ix_certificates_section'))
        batch_op.drop_index(batch_op.f('ix_certificates_reg_type'))
        batch_op.drop_index('ix_certificates_cir')
        batch_op.drop_index(batch_op.f('ix_certificates_category'))

    op.drop_table('certificates')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_occurred')
        batch_op.drop_index(batch_op.f('ix_audit_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_audit_events_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_events_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_actor_email'))
        batch_op.drop_index(batch_op.f('ix_audit_events_action'))
        batch_op.drop_index('ix_audit_entity')

    op.drop_table('audit_events')
    # ### end Alembic commands ###
